### ISSUE TITLE
For the imports as well please

### ISSUE THREAD

**Issue by fxfactorial** [ChainSafe/truffle-plugin-abigen#3]
is it possible to also have this build against whatever imports are used in the contracts as well? 

```
import '@foo/bar/Something.sol';
```

and also have the abigen respective files be built against Something.sol 

thank you so much for this package,

**Comment by GregTheGreek** [comment]
@fxfactorial hey! I made this sort of for myself, but absoutely!

I can take a look at this in the morning!

Do you mind explaining what exactly you mean? Does it only compile one contract? If so I think I remember that, and I had to pass all the contracts in the cli manually.... 

If thats the case i can definitely do it :)

**Comment by fxfactorial** [comment]
the best builders build for themselves! 

like for example, 

in my contract i have:

```
import '@openzeppelin/contracts/token/ERC20/IERC20.sol';
import '@openzeppelin/contracts/token/ERC20/SafeERC20.sol';
import '@uniswap/v2-core/contracts/interfaces/IUniswapV2Pair.sol';
```

but as the plugin is now, the only built .jsons are my `MyContract.json`, but i still need in abigen the `IERC20` and `IUniswapV2Pair`

currently i just did the abigen myself, added this plugin to uniswap itself and built there, then copy in my project, but better if it could have in my main project where i use this plugin

**Comment by GregTheGreek** [comment]
ahhhh yes .... soo I had this problem but I was using it in a script so for whatever reason it didn't occur to me to actually do it how you described. Right now it works if you do (which is what we were using for a project):
```
truffle run abigen MyContract IERC20 .... etc
```

I'll take a stab in a few hours :)

**Comment by GregTheGreek** [comment]
@fxfactorial hey sorry i got really busy. Do you mind checking out https://github.com/ChainSafe/truffle-plugin-abigen/pull/4 it should fix it for you :)

**Comment by fxfactorial** [comment]
@GregTheGreek awesome - thank you - will try out soon

**Comment by fxfactorial** [comment]
ya - seems to work!

**Comment by GregTheGreek** [comment]
merging to master and cutting a release :)
